import styles from "./index.module.scss";

import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.image}>
          <Image src="/chat.svg" alt="Chat" layout="fill" />
        </div>
        <div className={styles.content}>
          <h1>Enjoy the new experience of chatting with global friends</h1>
          <p>Connect people around the world for free</p>
          <button>
            <Link href="/auth/login">
              <a>Get Started</a>
            </Link>
          </button>
        </div>
      </main>
    </div>
  );
};

export default Home;
